### PR TITLE
Blind reorganization

### PR DESCRIPTION
**Pull request by jkamins7**
What do people think of doing a reorganization like this.  Obviously this particular thing would break a bunch of stuff and can't work.  But if we were going to put in the work to restructure, is this a structure we like?

### CODE REVIEW

**Comment by eclee25** [comment]
I think a restructure like this would be good. One question though: in report_generation (which should be renamed!), why do we need the templates/state_report/skeleton/skeleton.Rmd structure? Is it a default? My thought is just to put skeleton.Rmd in state_report/

**Comment by jlessler** [comment]
> I think a restructure like this would be good. One question though: in report_generation (which should be renamed!), why do we need the templates/state_report/skeleton/skeleton.Rmd structure? Is it a default? My thought is just to put skeleton.Rmd in state_report/

The location of skeleton.Rmd for templates in the skeleton directory is dictated by RStudio. I think it is because the "skeleton" often consists of more than one file (e.g., the bib file in our case)

**Comment by jcblemai** [comment]
I like this reorganisation. Especially because the past "programming language split" (python/ vs R/) does not bring any info to the user (if I'm looking for importation, where should I go). So it's very sensible.

**Comment by jkamins7** [comment]
@jwills recommended keeping the build scripts separate, e.g., in a build folder rather than scripts, which i think is sensible

**Comment by jkamins7** [comment]
I think we can.  It's probably more important to have it in the packages directory

**Comment by Perif** [comment]
For the packages organization one could also consider an alternative:

```
packages/R/pkg1
packages/R/pkg2
packages/R/requirements.R
packages/R/requirements-custom.R
packages/python/requirements.txt
```

In this PR the install related files (`requirement.txt` for Python and `packages.R` files are located in the scripts directory which mixes the concerns between package management and core scripts such as `simulate.py`.

Perhaps using a script directory and a package directory with a distinction per language can help to discriminate package management and core functions

**Pull request closed without merging**
