### PR TITLE
Some minimalist changes to the python code that I think should make the core loop faster

### PR DESCRIPTION
**Pull request by jwills**
1) Skip ori-dest pairs that don't have any travel between them in updating the y values.
2) Vectorize the calls to np.random.binomial and eliminate the loop over nnodes (this one seemed a bit iffier to me if the JIT is doing its thing, but the code seemed cleaner and more consistent w/the other vectorized bits of the loop.)

Was going to try this out later tonight against the minimalist config and see how it goes!

### CODE REVIEW

**Comment by jwills** [comment]
Related: would love to do a more extensive optimization of the mobility data and code to prefer a sparse-matrix format for ingest and move some of the repetitive bits of the mobility computations out of the main temporal loop. @jcblemai

**Comment by jwills** [comment]
Did some testing with this tonight, and my conclusion was actually a surprise to me- we need to throw the jit out to the curb- I don't think it's doing us any performance favors when we're combining it with the multiprocessing module. I can run 1000 sims of the minimalist scenario in 48 seconds on a 4 core machine on AWS if I disable the JIT entirely and add in this simple filter on the mobility matrix.

**Comment by jwills** [comment]
```(python_venv)  392605ae29a1:~/src$ python3 COVIDScenarioPipeline//simulate.py -c config.yml  -s None -n 1000 -j 4
Scenarios to be run: None

>> Scenario: None
>> Starting 1000 model runs on 4 processes
>> Setup *** minimal_None *** from 2020-01-31 to 2020-05-31
>> writing to folder : model_output/minimal_None/minimal_None
    
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:48<00:00, 20.75it/s]

>> 1000 simulations completed in 48.3 seconds```

**Comment by jcblemai** [comment]
You mean it's faster without jit ? My initial benchmark were really not showing this on the west coast setup. I think it's because the minimal setup is very small and the time range is short too. Would you mind sharing benchmark results ?

**Comment by jkamins7** [comment]
yeah, @jwills the minimal branch only has 2 geoids, so it might not really appropriate for time testing this loop.

**Pull request closed without merging**
